site_name: Learn python with cat
site_url: https://github.com/mickche/learn_python
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  font:
    text: PT Sans

  features:
    - content.tabs.link
    - navigation.footer
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключити на темну тему

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключити на світлу тему

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickche

nav:
  - Головна: hello.md
  - Перша программа: first.md
  - Змінні та математичні дії:
      - Математичні дії в Python: math.md
      - Вступ до змінних: start_variables.md
      - Робота зі змінними: variables.md

markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - "python_file"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
