site_name: Learn python with cat
site_url: https://github.com/mickche/learn_python

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  font:
    text: PT Sans

  features:
    - content.tabs.link
    - navigation.footer
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключити на темну тему

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключити на світлу тему

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

  - javascripts/quiz.js

nav:
  - Головна: hello.md
  - Перша програма: first.md
  - Змінні та математичні дії:
      - Математичні дії в Python: math.md
      - Робота зі змінними: variables.md

  - Списки: list.md

  - Цикли: for.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.superfences

  - pymdownx.inlinehilite

  - admonition

  - pymdownx.details

  - pymdownx.mark

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickche
